"""create initial product schema

Revision ID: db81de89b2b5
Revises:
Create Date: 2026-09-29 07:45:43.457340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db81de89b2b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='project_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('target_duration_seconds', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('split_policy', sa.Enum('SINGLE', 'AUTO_SPLIT', 'USER_CONFIRM_SPLIT', name='episode_split_policy', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_duration_seconds IS NULL OR target_duration_seconds > 0', name='ck_projects_target_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('source_videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_reference', sa.String(length=1024), nullable=False),
    sa.Column('fingerprint', sa.String(length=512), nullable=True),
    sa.Column('fingerprint_algorithm', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('video_codec', sa.String(length=64), nullable=True),
    sa.Column('audio_codec', sa.String(length=64), nullable=True),
    sa.Column('format_name', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('processing_status', sa.Enum('REGISTERED', 'READY', 'PROCESSING', 'COMPLETED', 'FAILED', name='source_video_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(fingerprint IS NULL AND fingerprint_algorithm IS NULL) OR (fingerprint IS NOT NULL AND fingerprint_algorithm IS NOT NULL)', name='ck_source_videos_fingerprint_pair'),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_source_videos_duration_nonnegative'),
    sa.CheckConstraint('fps IS NULL OR fps > 0', name='ck_source_videos_fps_positive'),
    sa.CheckConstraint('height IS NULL OR height > 0', name='ck_source_videos_height_positive'),
    sa.CheckConstraint('width IS NULL OR width > 0', name='ck_source_videos_width_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_videos_processing_status', 'source_videos', ['processing_status'], unique=False)
    op.create_index('ix_source_videos_project_id', 'source_videos', ['project_id'], unique=False)
    op.create_table('processing_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_video_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('PROBE', 'AUDIO_EXTRACTION', 'STT', 'MEMO_DETECTION', name='processing_stage_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='processing_stage_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('safe_error_code', sa.String(length=64), nullable=True),
    sa.Column('safe_error_message', sa.String(length=512), nullable=True),
    sa.Column('input_fingerprint', sa.String(length=512), nullable=True),
    sa.Column('config_version', sa.String(length=128), nullable=True),
    sa.Column('tool_version', sa.String(length=128), nullable=True),
    sa.Column('result_version', sa.String(length=128), nullable=True),
    sa.Column('result_reference', sa.String(length=1024), nullable=True),
    sa.Column('result_fingerprint', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='ck_processing_stages_attempt_nonnegative'),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_video_id', 'stage', name='uq_processing_stages_source_stage')
    )
    op.create_index('ix_processing_stages_source_video_id', 'processing_stages', ['source_video_id'], unique=False)
    op.create_index('ix_processing_stages_status', 'processing_stages', ['status'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_video_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('language_probability', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('language_probability IS NULL OR (language_probability >= 0 AND language_probability <= 1)', name='ck_transcripts_language_probability_range'),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_video_id', name='uq_transcripts_source_video_id')
    )
    op.create_table('edit_memos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_video_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('start_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('end_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('matched_trigger', sa.String(length=255), nullable=False),
    sa.Column('matched_reference', sa.String(length=255), nullable=False),
    sa.Column('matched_action', sa.String(length=255), nullable=False),
    sa.Column('trigger_match_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_similarity', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_seconds >= start_seconds', name='ck_edit_memos_time_order'),
    sa.CheckConstraint('start_seconds >= 0', name='ck_edit_memos_start_nonnegative'),
    sa.CheckConstraint('trigger_similarity >= 0 AND trigger_similarity <= 1', name='ck_edit_memos_trigger_similarity_range'),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edit_memos_source_video_id', 'edit_memos', ['source_video_id'], unique=False)
    op.create_index('ix_edit_memos_transcript_id', 'edit_memos', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edit_memos_transcript_id', table_name='edit_memos')
    op.drop_index('ix_edit_memos_source_video_id', table_name='edit_memos')
    op.drop_table('edit_memos')
    op.drop_table('transcripts')
    op.drop_index('ix_processing_stages_status', table_name='processing_stages')
    op.drop_index('ix_processing_stages_source_video_id', table_name='processing_stages')
    op.drop_table('processing_stages')
    op.drop_index('ix_source_videos_project_id', table_name='source_videos')
    op.drop_index('ix_source_videos_processing_status', table_name='source_videos')
    op.drop_table('source_videos')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
